config/routes.rb
Rails.application.routes.draw do
	root 'posts#index'
  post '/russ_posts/new', to: 'russ_posts#new'
  resources :russ_posts
  resources :contacts, only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
	resources :posts
	
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attributes :name,  :validate => true
  attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message
  attributes :nickname,   :captcha => true


   def headers
    {
      :to => "nikcochran@gmail.com",
      :subject => "Contact Form",
      :from => %("#{name}" <#{email}>)
    }
	end
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true

	 has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
 	 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/russ_post.rb
class RussPost < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new 
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new 
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def show
		@posts = Post.find(params[:id])
		@posts = Post.order("created_at desc").limit(4).offset(1)
	end


	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/russ_posts_controller.rb
class RussPostsController < InheritedResources::Base

  # private

    def russ_post_params
      params.require(:russ_post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/russ_posts_helper.rb
module RussPostsHelper
end

app/views/contacts/create.html.erb
<div class="thanks">
	<h1>Thank's for the message.</h1>
	<p>I'll get back to you when I feel like it.</p>
</div>

  <%= image_tag "BertrandPipe.png", class: "bertrand-pipe" %>

app/views/contacts/new.html.erb
<h1 id="page_title">Contact</h1>
<div class="contact-style">
	<div class="skinny_wrapper wrapper_padding">
		<%= form_for @contact do |f| %>
			<%= f.label :name, class: 'contact_name' %><br>
			<%= f.text_field :name, required: true %>

			<br>

			<%= f.label :email %><br>
			<%= f.email_field :email, required: true %>
			
			<br>

			<%= f.label :message %><br>
			<%= f.text_area :message, as: :text %>

			<div class="hidden">
				<%= f.label :nickname %><br>
				<%= f.text_field :nickname, hint: 'leave this field blank' %>
			</div>

	  		<div class="contact-button">
	  			<%= f.submit 'Send Message', class: "contact-button" %>
	  		</div>

	  		<% end %>
	  	</div>
	 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Russell Conjugation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>

  <%= render 'shared/header' %>
  <%= render 'shared/alerts' %>
  <%= yield %>
  <%= render 'shared/footer' %>
  
  </body>
</html>

app/views/posts/index.html.erb
<!-- Header -->
<header>
<div class="evaluate">
    <%= button_to "Click To Evaluate Text", new_russ_post_url %>
</div>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <%= image_tag "BertrandNeutral.png", class: "img-responsive" %>
                <div class="intro-text">
                    <span class="name">Russell Conjugation</span>
                    <hr class="star-light">
                    <span class="skills">Taking Out The Emotion</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Portfolio Grid Section -->
<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="concept-title">Concept</h2>
                <p>From Edge.org(Eric Weinstein)<br>"In order to understand the concept properly you have to appreciate that most words and phrases are actually defined not by a single dictionary description, but rather two distinct attributes:<br>

I) The factual content of the word or phrase.<br>
II) The emotional content of the construction.<br>

Where words can be considered “synonyms” if they carry the same factual content (I) regardless of the emotional content (II). This however leads to the peculiar effect that the synonyms for a positive word like “whistle-blower” cannot be used in its place as they are almost universally negative (with “snitch,” “fink,” “tattletale” being representative examples). This is our first clue that something is wrong, or at least incomplete with our concept of synonym requiring an upgrade to distinguish words that may be content synonyms but emotional antonyms.<br>

The basic principle of Russell Conjugation is that the human mind is constantly looking ahead well beyond what is true or false to ask “What is the social consequence of accepting the facts as they are?”  While this line of thinking is obviously self-serving, we are descended from social creatures who could not safely form opinions around pure facts so much as around how those facts are presented to us by those we ape, trust or fear. Thus, as listeners and readers our minds generally mirror the emotional state of the source, while in our roles as authoritative narrators presenting the facts, we maintain an arsenal of language to subliminally instruct our listeners and readers on how we expect them to color their perceptions. Russell discussed this by putting three such presentations of a common underlying fact in the form in which a verb is typically conjugated:<br>

I am firm. [Positive empathy]<br>
You are obstinate. [Neutral to mildly negative empathy]<br>
He/She/It is pigheaded.  [Very negative empathy]<br>

In all three cases, Russell was describing people who did not readily change their minds. Yet by putting these descriptions so close together and without further factual information to separate the individual cases, we were forced to confront the fact that most of us feel positively towards the steadfast narrator and negatively towards the pigheaded fool, all without any basis in fact."
</p>
            </div>
        </div>
        <div class="row">
                <% @posts.each do |post| %>
                <div class="col-sm-4 portfolio-item">
                <%= link_to post_path(post) do %>
                  <%= image_tag post.image, class: 'img-post' %>
                <% end %>
                </div>
            <% end %>
        </div>
    </div>
</section>

<!-- About Section -->
<section class="success" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>About</h2>
                <hr class="star-light">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 paragraph-content">
 <p>This site was created to help combat the manipulative nature of the news media. After first hearing about the concept from Eric Weinstein, I began looking deeper into the impact our emotions have over how we view the world and how these emotions can, in turn, impede our rationality. This site in its current state is heavily flawed but aims to serve as a proof of concept in how we might begin to address this issue, which in today's political climate can have catastrophic real world implications.<br><br>If you would like to work on this project or use this code for any purpose, you can access the GitHub page through the link in the footer.</p>
            </div>

        
        </div>
    </div>
</section>

app/views/posts/show.html.erb
<!-- Page Content -->
<div class="container post-container">

    <!-- Portfolio Item Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><%= @post.title %>
                <small>Item Subheading</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <%= image_tag @post.image, class: 'img-responsive' %>
        </div>

        <div class="col-md-4">
            <h3>Project Description</h3>
            <p><%= @post.body %></p>
        </div>

    </div>
    <!-- /.row -->

    <!-- Related Projects Row -->
    <div class="row">

        <div class="col-lg-12">
            <h3 class="page-header">Related Projects</h3>
        </div>

        <% @posts.each do |post| %>
            <div class="col-sm-3 col-xs-6">
                <%= link_to post_path(post) do %>
                  <%= image_tag post.image, class: 'img-responsive portfolio-item' %>
                <% end %>
            </div>
        <% end %>

    </div>
    <!-- /.row -->
</div>

app/views/russ_posts/_form.html.erb
<%= form_for(russ_post) do |f| %>
  <% if russ_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(russ_post.errors.count, "error") %> prohibited this russ_post from being saved:</h2>

      <ul>
      <% russ_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.trix_editor :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/russ_posts/edit.html.erb
<h1>Editing Russ Post</h1>

<%= render 'form', russ_post: @russ_post %>

<%= link_to 'Show', @russ_post %> |
<%= link_to 'Back', posts_path %>

app/views/russ_posts/new.html.erb
<link rel="stylesheet" type="text/css" href="/assets/trix.css">
<script type="text/javascript" src="/assets/trix.js"></script>


<h1 class="enter-text">Enter or Paste Text Below</h1>
<h6 class="sub-text">(Text less than a paragraph long will have diminished accuracy)</h6>

<%= render 'form', russ_post: @russ_post %>

<%= link_to 'Back', posts_path, class: "button" %>

app/views/shared/_alerts.html.erb
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
  <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Location</h3>
                        <p>1234 Rational Avenue
                            <br>World Wide, EA 00000</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Share Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="https://www.facebook.com/" class="btn-social btn-outline"><span class="sr-only">Facebook</span><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/" class="btn-social btn-outline"><span class="sr-only">Google Plus</span><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="https://twitter.com/" class="btn-social btn-outline"><span class="sr-only">Twitter</span><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/" class="btn-social btn-outline"><span class="sr-only">Linked In</span><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                              <li>
                                <a href="https://www.instagram.com/" class="btn-social btn-outline"><span class="sr-only">Instagram</span><i class="fa fa-fw fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>GitHub</h3>
                        <p>Russell Conjugation is open source. Feel free to do what you like with it and improve upon this basic idea. <a href="https://github.com/NikValdez/russell_conjugation" class= "visit">Visit Repo</a></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Nerdvestor 2017
                    </div>
                </div>
            </div>
        </div>
    </footer>

app/views/shared/_header.html.erb
    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/posts">Russell Conjugation</a>
            </div>




            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="/posts#portfolio">Concept</a>
                    </li>
                    <li class="page-scroll">
                        <a href="/posts#about">About</a>
                    </li>
                    <li class="page-scroll">
                        <a href="/contacts/new">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>